name: ubuntu_welcome
description: Ubuntu Welcome
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.0
  ubuntu_init:
    path: vendor/ubuntu-desktop-provision/packages/ubuntu_init

dev_dependencies:
  flutter_lints: ^3.0.0
  melos: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
