name: ubuntu-welcome
version: git
summary: Ubuntu Welcome
description: |
  Ubuntu Welcome description.
grade: stable
confinement: strict
base: core22
issues: https://github.com/canonical/ubuntu-welcome/issues
contact: https://github.com/canonical/ubuntu-welcome/issues
architectures:
  - build-on: amd64
  - build-on: arm64

plugs:
  dot-config-ubuntu-welcome-done:
    interface: personal-files
    write:
      - $HOME/.config/ubuntu-welcome-done

apps:
  ubuntu-welcome:
    command: bin/ubuntu_welcome
    extensions: [gnome]
    desktop: bin/data/flutter_assets/assets/ubuntu-welcome.desktop
    environment:
      LOG_LEVEL: debug
    plugs:
      - desktop-launch
      - hardware-observe
      - log-observe
      - system-observe
      - dot-config-ubuntu-welcome-done

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.10.5
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  ubuntu-welcome:
    after: [flutter-git]
    source: .
    source-type: git
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/bin/lib
      flutter pub get
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    stage-packages:
      - libsysmetrics1
      - pciutils
      - util-linux

lint:
  ignore:
    - library:
        - usr/lib/**/libsysmetrics.so.1

slots:
  dbus-name:
    interface: dbus
    bus: session
    name: com.canonical.ubuntu_welcome
